"""create stripe id property and image url property

Revision ID: 5ca74916f085
Revises: a9684c3493a5
Create Date: 2023-03-07 06:20:44.050344+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5ca74916f085"
down_revision = "a9684c3493a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("projects", sa.Column("image_url", sa.String(), nullable=True))
    op.execute(
        "UPDATE projects SET image_url = 'https://arbordayblog.org/wp-content/uploads/2016/06/tree.jpg' WHERE image_url IS NULL"
    )
    op.add_column("transactions", sa.Column("stripe_id", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("transactions", "stripe_id")
    op.drop_column("projects", "image_url")

    # ### end Alembic commands ###
