"""add 1 column

Revision ID: 685e54fdd34e
Revises: e60aac752266
Create Date: 2022-09-27 21:49:48.946327+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "685e54fdd34e"
down_revision = "e60aac752266"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("new_col", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "new_col")
    # ### end Alembic commands ###
