"""remove redundant columns

Revision ID: 84bd6bafac82
Revises: 66900c0c2bf5
Create Date: 2022-10-16 17:22:15.562554+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "84bd6bafac82"
down_revision = "66900c0c2bf5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("users", "is_project_owner")
    op.drop_column("users", "is_backer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_backer", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("is_project_owner", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )

    # ### end Alembic commands ###
