"""remove test column

Revision ID: 8b768cc35668
Revises: 685e54fdd34e
Create Date: 2022-09-28 17:38:38.523434+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8b768cc35668"
down_revision = "685e54fdd34e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("projects", "new_col")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("new_col", sa.INTEGER(), autoincrement=False, nullable=True),
    )

    # ### end Alembic commands ###
