"""add refund id column to transaction

Revision ID: a0e8ecc6fd09
Revises: 257b66d9f085
Create Date: 2023-02-07 06:30:39.350894+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a0e8ecc6fd09"
down_revision = "257b66d9f085"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("transactions", sa.Column("refund_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "transactions", "refunds", ["refund_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "refund_id")

    # ### end Alembic commands ###
