"""create payout table

Revision ID: a9684c3493a5
Revises: a0e8ecc6fd09
Create Date: 2023-02-11 09:01:32.384447+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9684c3493a5'
down_revision = 'a0e8ecc6fd09'
branch_labels = None
depends_on = None

from app.schemas.transaction_status import TransactionStatus
from app.schemas.currency import Currency


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    transactionstatus = postgresql.ENUM(
        TransactionStatus, name="transactionstatus", create_type=False
    )
    transactionstatus.create(op.get_bind(), checkfirst=True)
    currency_enum = postgresql.ENUM(Currency, name="currency_enum", create_type=False)
    currency_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', transactionstatus, nullable=True),
    sa.Column('currency', currency_enum, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_id'), 'payouts', ['id'], unique=True)
    op.create_index(op.f('ix_payouts_project_id'), 'payouts', ['project_id'], unique=True)
    op.create_index(op.f('ix_payouts_user_id'), 'payouts', ['user_id'], unique=True)
    
    op.alter_column('transactions', 'date_ordered',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    
    op.drop_constraint('transactions_refund_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'refund_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('refund_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('transactions_refund_id_fkey', 'transactions', 'refunds', ['refund_id'], ['id'])    
    op.alter_column('transactions', 'date_ordered',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_payouts_user_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_project_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_id'), table_name='payouts')
    op.drop_table('payouts')
    # ### end Alembic commands ###
