"""add projects table and tags table

Revision ID: d6081b2fc5dc
Revises: 88c449c9ae11
Create Date: 2022-08-23 16:10:42.679942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6081b2fc5dc"
down_revision = "88c449c9ae11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_projects_id", table_name="projects")
    op.drop_table("projects")
    op.drop_table("project_tags")
    op.drop_table("notes")
    op.drop_index("ix_tags_id", table_name="tags")
    op.drop_table("tags")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('tags_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="tags_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_tags_id", "tags", ["id"], unique=False)
    op.create_table(
        "notes",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("completed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="notes_pkey"),
    )
    op.create_table(
        "project_tags",
        sa.Column("project_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tag_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="project_tags_project_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name="project_tags_tag_id_fkey"
        ),
        sa.PrimaryKeyConstraint("project_id", "tag_id", name="project_tags_pkey"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("completed", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="projects_pkey"),
    )
    op.create_index("ix_projects_id", "projects", ["id"], unique=False)
    # ### end Alembic commands ###
