# """create backer project table

# Revision ID: 7aa6997fcbb1
# Revises: 84bd6bafac82
# Create Date: 2022-10-19 17:37:28.371973+00:00

# """
# from alembic import op
# import sqlalchemy as sa
# from sqlalchemy.dialects import postgresql

# # revision identifiers, used by Alembic.
# revision = "7aa6997fcbb1"
# down_revision = "84bd6bafac82"
# branch_labels = None
# depends_on = None


# def upgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.create_table(
#         "backers_projects_orders",
#         sa.Column("id", sa.Integer(), nullable=False, unique=True),
#         sa.Column("backer_id", sa.Integer(), nullable=False),
#         sa.Column("project_id", sa.Integer(), nullable=False),
#         sa.Column("quantity", sa.Integer(), nullable=False),
#         sa.Column("amount", sa.Float(), nullable=False),
#         sa.Column("date_ordered", sa.DateTime(timezone=True), nullable=True),
#         sa.Column(
#             "status",
#             sa.Enum(
#                 "SUCCESS",
#                 "PENDING",
#                 "CANCELLED",
#                 "BANNED",
#                 name="backerstatus",
#             ),
#             nullable=True,
#         ),
#         sa.Column(
#             "currency",
#             sa.Enum(
#                 "USD",
#                 "EUR",
#                 name="currency",
#             ),
#             nullable=True,
#         ),
#         sa.PrimaryKeyConstraint("id"),
#         sa.ForeignKeyConstraint(
#             ["backer_id"],
#             ["users.id"],
#         ),
#         sa.ForeignKeyConstraint(
#             ["project_id"],
#             ["projects.id"],
#         ),
#     )
#     op.create_index(
#         op.f("ix_backers_projects_orders_backer_id"),
#         "backers_projects_orders",
#         ["backer_id"],
#         unique=True,
#     )
#     op.create_index(
#         op.f("ix_backers_projects_orders_project_id"),
#         "backers_projects_orders",
#         ["project_id"],
#         unique=True,
#     )
#     op.create_index(
#         op.f("ix_backers_projects_orders_id"),
#         "backers_projects_orders",
#         ["id"],
#         unique=True,
#     )
#     op.add_column("projects", sa.Column("credits_sold", sa.Integer(), nullable=True))
#     op.alter_column(
#         "projects", "needed_credits", nullable=False, new_column_name="new_col_name"
#     )
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column(
#         "projects",
#         sa.Column("needed_credits", sa.INTEGER(), autoincrement=False, nullable=True),
#     )
#     op.drop_column("projects", "credits_sold")
#     op.drop_index(
#         op.f("ix_backers_projects_orders_project_id"),
#         table_name="backers_projects_orders",
#     )
#     op.drop_index(
#         op.f("ix_backers_projects_orders_backer_id"),
#         table_name="backers_projects_orders",
#     )
#     op.drop_index(
#         op.f("ix_backers_projects_orders_id"),
#         table_name="backers_projects_orders",
#     )
#     op.drop_table("backers_projects_orders")
#     # ### end Alembic commands ###
