name: CI

on:
  push:
    branches: ["main, dev"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow

      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.9
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: Lint with black
        run: |
          pipenv run lint
          pipenv run lintcheck
      - name: Test with pytest
        run: pipenv run dev