name: CI

on:
  push:
    branches: ["main, dev"]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow

      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.9
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: Lint with black
        run: |
          pipenv run lint
          pipenv run lintcheck
      # - name: Test with pytest
      #   run: pipenv run test
      #   env:
      #     DATABASE_URL: postgres://postgres:postgres@localhost/postgres

